import {useEffect,useMemo,useRef,useState} from 'react'
import {Copy,Eye,GripVertical,MoreHorizontal,Plus,Redo2,SplitSquareHorizontal,SplitSquareVertical,Trash2,Undo2,X} from 'lucide-react'
import {clone,collect,createWidget,firstLeaf,find,id,isLeaf,remove,setRatio,split,starter,update,widgetName,type Direction, type Node, type Widget, type WidgetType, type Snapshot} from './model'
import {catalog,WidgetView} from './widgets'

const STORAGE='widget-editor-clean-v1'
const save=(s:Snapshot)=>localStorage.setItem(STORAGE,JSON.stringify(s))
const load=():Snapshot|null=>{try{const x=localStorage.getItem(STORAGE);return x?JSON.parse(x):null}catch{return null}}

export function App(){
 const [snapshot,setSnapshot]=useState<Snapshot>(()=>load()||starter()); const [selected,setSelected]=useState<string|null>(null); const [mode,setMode]=useState<'edit'|'preview'>('edit'); const [settings,setSettings]=useState(false); const [catalogOpen,setCatalogOpen]=useState(false); const [past,setPast]=useState<Snapshot[]>([]); const [future,setFuture]=useState<Snapshot[]>([]); const [placing,setPlacing]=useState<WidgetType|null>(null)
 useEffect(()=>save(snapshot),[snapshot])
 const commit=(next:Snapshot)=>{setPast(p=>[...p.slice(-49),clone(snapshot)]);setFuture([]);setSnapshot(next)}
 const undo=()=>{const p=past.at(-1);if(!p)return;setFuture(f=>[clone(snapshot),...f]);setPast(past.slice(0,-1));setSnapshot(p)}
 const redo=()=>{const n=future[0];if(!n)return;setPast(p=>[...p,clone(snapshot)]);setFuture(future.slice(1));setSnapshot(n)}
 const place=(leafId:string,type:WidgetType)=>{const w=createWidget(type);let widgets={...snapshot.widgets,[w.id]:w};let root=update(snapshot.root,leafId,n=>isLeaf(n)?{...n,widgetId:w.id}:n);const old=find(snapshot.root,leafId);if(old&&isLeaf(old)&&old.widgetId){const oldId=old.widgetId;delete widgets[oldId]}commit({root,widgets});setSelected(leafId);setPlacing(null);setCatalogOpen(false)}
 const move=(from:string,to:string)=>{const a=find(snapshot.root,from),b=find(snapshot.root,to);if(!a||!b||!isLeaf(a)||!isLeaf(b)||from===to)return;let root=update(snapshot.root,from,n=>isLeaf(n)?{...n,widgetId:b.widgetId}:n);root=update(root,to,n=>isLeaf(n)?{...n,widgetId:a.widgetId}:n);commit({root,widgets:snapshot.widgets});setSelected(to)}
 const duplicate=(leafId:string)=>{const n=find(snapshot.root,leafId);if(!n||!isLeaf(n))return;let wmap=snapshot.widgets;let wid:string|null=null;if(n.widgetId){const old=snapshot.widgets[n.widgetId];if(old){const w=clone(old);w.id=id('widget');wmap={...wmap,[w.id]:w};wid=w.id}}const root=split(snapshot.root,leafId,'vertical',wid);const created=find(root,leafId);let targetLeaf:string|null=null;if(created&&created.kind==='split')targetLeaf=created.second.id;commit({root,widgets:wmap});setSelected(targetLeaf||leafId)}
 const deleteArea=(leafId:string)=>{const leaves=collect(snapshot.root);let root=leaves.length<=1?update(snapshot.root,leafId,n=>isLeaf(n)?{...n,widgetId:null}:n):remove(snapshot.root,leafId);const keep=new Set(collect(root));const widgets=Object.fromEntries(Object.entries(snapshot.widgets).filter(([k])=>keep.has(k)));commit({root,widgets});setSelected(null)}
 const changeRatio=(splitId:string,r:number)=>setSnapshot(s=>({root:setRatio(s.root,splitId,r),widgets:s.widgets}))
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{const meta=e.ctrlKey||e.metaKey;if(meta&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if(meta&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.key==='Escape'){setPlacing(null);setSelected(null)}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[past,future,snapshot])
 return <div className="app">
  <header className="topbar"><div className="brand"><strong>Экран</strong><span>конструктор</span></div><div className="toolbar"><button disabled={!past.length} onClick={undo} title="Отменить"><Undo2/></button><button disabled={!future.length} onClick={redo} title="Вернуть"><Redo2/></button></div><div className="top-actions"><button className="mobile-only" onClick={()=>setCatalogOpen(true)}>Виджеты</button><button onClick={()=>setMode(mode==='edit'?'preview':'edit')} className="primary">{mode==='edit'?<><Eye/>Просмотр</>:<>Редактировать</>}</button><button className="icon" onClick={()=>setSettings(true)}><MoreHorizontal/></button></div></header>
  {placing&&<div className="placing">Выберите область для «{widgetName[placing]}» · Esc — отмена</div>}
  <div className="workspace">
   {mode==='edit'&&<aside className="catalog"><div className="panel-title">ВИДЖЕТЫ</div><div className="catalog-list">{catalog.map(x=><CatalogItem key={x.type} item={x} onPick={()=>selected?place(selected,x.type):setPlacing(x.type)}/>)}</div></aside>}
   <main className={mode==='edit'?'canvas-area edit-canvas':'canvas-area preview-canvas'} onClick={()=>mode==='edit'&&setSelected(null)}><Canvas node={snapshot.root} snapshot={snapshot} selected={selected} setSelected={setSelected} placing={placing} place={place} move={move} split={d=>commit({root:split(snapshot.root,d, 'vertical'),widgets:snapshot.widgets})} duplicate={duplicate} deleteArea={deleteArea} changeRatio={changeRatio} mode={mode}/></main>
   {mode==='edit'&&<aside className="settings"><div className="panel-title">НАСТРОЙКИ</div><Inspector snapshot={snapshot} selected={selected} commit={commit}/></aside>}
  </div>
  {catalogOpen&&<div className="mobile-sheet" onClick={()=>setCatalogOpen(false)}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="sheet-head">Виджеты <button onClick={()=>setCatalogOpen(false)}><X/></button></div>{catalog.map(x=><CatalogItem key={x.type} item={x} onPick={()=>{selected?place(selected,x.type):setPlacing(x.type);setCatalogOpen(false)}}/>)}</div></div>}
  {settings&&<div className="mobile-sheet" onClick={()=>setSettings(false)}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="sheet-head">Настройки <button onClick={()=>setSettings(false)}><X/></button></div><Inspector snapshot={snapshot} selected={selected} commit={commit}/></div></div>}
 </div>
}
function CatalogItem({item,onPick}:{item:typeof catalog[number];onPick:()=>void}){const Icon=item.icon;return <button className="catalog-item" onClick={onPick} draggable onDragStart={e=>e.dataTransfer.setData('widget-type',item.type)}><span className="catalog-icon"><Icon/></span><span><b>{widgetName[item.type]}</b><small>{item.hint}</small></span></button>}
function Canvas(p:{node:Node;snapshot:Snapshot;selected:string|null;setSelected:(s:string|null)=>void;placing:WidgetType|null;place:(id:string,t:WidgetType)=>void;move:(a:string,b:string)=>void;split:(d:Direction)=>void;duplicate:(id:string)=>void;deleteArea:(id:string)=>void;changeRatio:(id:string,r:number)=>void;mode:'edit'|'preview'}){if(p.node.kind==='split')return <SplitView {...p} node={p.node}/>;const n=p.node;const w=n.widgetId?p.snapshot.widgets[n.widgetId]:null;return <div className={'leaf '+(p.selected===n.id?'selected':'')} onClick={e=>{e.stopPropagation();p.setSelected(n.id)}} onDragOver={e=>{if(p.mode==='edit')e.preventDefault()}} onDrop={e=>{e.preventDefault();const t=e.dataTransfer.getData('widget-type');const from=e.dataTransfer.getData('from-leaf');if(t)p.place(n.id,t as WidgetType);else if(from)p.move(from,n.id)}}>{w?<WidgetView widget={w}/>:p.mode==='edit'?<div className="empty"><Plus/><span>Добавить виджет</span></div>:null}{p.mode==='edit'&&p.selected===n.id&&<div className="leaf-actions"><button title="Разделить горизонтально" onClick={e=>{e.stopPropagation();p.split('horizontal')}}><SplitSquareHorizontal/></button><button title="Разделить вертикально" onClick={e=>{e.stopPropagation();p.split('vertical')}}><SplitSquareVertical/></button><button title="Дублировать" onClick={e=>{e.stopPropagation();p.duplicate(n.id)}}><Copy/></button><button title="Удалить" onClick={e=>{e.stopPropagation();p.deleteArea(n.id)}}><Trash2/></button><span className="drag-handle" draggable onDragStart={e=>{e.stopPropagation();e.dataTransfer.setData('from-leaf',n.id)}}><GripVertical/></span></div>}</div>}
function SplitView(p:any){const n=p.node as Extract<Node,{kind:'split'}>;const ref=useRef<HTMLDivElement>(null);return <div ref={ref} className={'split '+n.direction} onPointerMove={e=>{if((ref.current as any)?.dragging){const r=ref.current!.getBoundingClientRect();p.changeRatio(n.id,n.direction==='vertical'?(e.clientX-r.left)/r.width:(e.clientY-r.top)/r.height)}}} onPointerUp={()=>{if(ref.current)(ref.current as any).dragging=false}}><div className="split-child" style={{flex:`${n.ratio} 1 0%`}}><Canvas {...p} node={n.first}/></div><div className="gutter" onPointerDown={e=>{e.preventDefault();(ref.current as any).dragging=true;(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}}></div><div className="split-child" style={{flex:`${1-n.ratio} 1 0%`}}><Canvas {...p} node={n.second}/></div></div>}
function Inspector({snapshot,selected,commit}:{snapshot:Snapshot;selected:string|null;commit:(s:Snapshot)=>void}){const node=selected?find(snapshot.root,selected):null;const w=node&&isLeaf(node)&&node.widgetId?snapshot.widgets[node.widgetId]:null;if(!w)return <div className="inspector-empty">Выберите область, чтобы настроить виджет.</div>;const patch=(x:Partial<Widget>)=>commit({...snapshot,widgets:{...snapshot.widgets,[w.id]:{...w,...x}}});return <div className="inspector"><div className="eyebrow">ВИДЖЕТ</div><h3>{widgetName[w.type]}</h3><label>Размер текста <input type="range" min="12" max="72" value={w.fontSize} onChange={e=>patch({fontSize:+e.target.value})}/><span>{w.fontSize}px</span></label><label>Прозрачность <input type="range" min="0.2" max="1" step="0.05" value={w.opacity} onChange={e=>patch({opacity:+e.target.value})}/></label><div className="seg"><button className={w.align==='left'?'on':''} onClick={()=>patch({align:'left'})}>Слева</button><button className={w.align==='center'?'on':''} onClick={()=>patch({align:'center'})}>Центр</button><button className={w.align==='right'?'on':''} onClick={()=>patch({align:'right'})}>Справа</button></div>{w.type==='weather'&&<label>Город<input value={w.city||''} onChange={e=>patch({city:e.target.value})}/></label>}{w.type==='text'&&<label>Текст<textarea value={w.text||''} onChange={e=>patch({text:e.target.value})}/></label>}{w.type==='metric'&&<label>Значение<input value={w.value||''} onChange={e=>patch({value:e.target.value})}/></label>}</div>}
